sudo: false
cache: pip

language: python

python:
    - 3.6
    - 3.5
    - 3.4
    - 3.3
    - 2.7

env:
  matrix:
    - TOXENV=py

matrix:
    include:
        - env: TOXENV=docs
        - env: TOXENV=manifest
    allow_failures:
        - python: "3.3"
        - python: "3.4"
        - python: "3.6"

before_install:
    - pip install codecov

install:
    - pip install tox

script:
    - tox

after_success:
    - tox -e coverage-report
    - codecov
